# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UtzniIkaUDNMO29ki7E4WWAUIqSUKHlI
"""



"""# Gene Prediction in Colab using Prodigal"""

# Install Prodigal (gene prediction tool)
# This command installs Prodigal on the Colab environment
!apt-get install prodigal -y

# Upload the FASTA file
from google.colab import files
fasta_file = "mycotb.fasta"

# Run Prodigal to predict genes
# -i: input FASTA file
# -a: output amino acid sequences (proteins)
# -d: output nucleotide sequences of predicted genes
# -f: output format (GFF)
# -o: output file with gene predictions

!prodigal -i mycotb.fasta -a proteins.faa -d genes.fna -f gff -o predicted.gff

"""predicted.gff: Genomic feature format: shows gene positions and coordinates

proteins.faa:	FASTA file of predicted protein sequences

genes.fna:	FASTA file of nucleotide sequences for the predicted ORFs
"""